HEADER = ["SEX","INSR_BEGIN","INSR_END","EFFECTIVE_YR","INSR_TYPE","INSURED_VALUE","PREMIUM","OBJECT_ID","PROD_YEAR","SEATS_NUM","CARRYING_CAPACITY","TYPE_VEHICLE","CCM_TON","MAKE","USAGE","CLAIM_PAID"]
NUM_FEATURES = ["INSURED_VALUE", "PREMIUM"]
CAT_FEATURES = ["SEX", "EFFECTIVE_YR", "INSR_TYPE", "SEATS_NUM","CARRYING_CAPACITY", "TYPE_VEHICLE"]