name: Background Training

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  background-training:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run training script with periodic artifact generation
      run: |
        for i in {1..5}; do  # Запускаем 5 итераций с задержкой
          python main.py --mode update  # Запускаем одну итерацию обучения
          sleep 10  # Задержка в 10 секунд между итерациями
        done

    - name: Upload logs
      uses: actions/upload-artifact@v4
      with:
        name: background-training-logs
        path: training.log

    - name: Upload usable model
      uses: actions/upload-artifact@v4
      with:
        name: model
        path: models/best_model.pkl
    
    - name: Cleanup
      run:
        make clean